"""
Mock AI Provider — used during M1/M2 development before the real AI provider
adapter is wired in M6.

The mock returns deterministic, schema-valid responses so that:
  - Flutter UI can be built and tested end-to-end without a live AI provider.
  - Backend can validate its own request/response parsing logic.
  - CI tests remain fast and reproducible (no network calls).

Replace this implementation in M6 with the real provider adapter
(see ADR-005 for the chosen provider and SDK).
"""

from __future__ import annotations

import logging

from app.models.schemas import (
    GenerateMode,
    GenerateRequest,
    GenerateResponse,
    RecommendationItem,
    RecommendationType,
)

logger = logging.getLogger(__name__)


class AIProviderService:
    """Stateless AI provider abstraction.

    In M6 this will delegate to the real provider SDK via an adapter interface.
    """

    @staticmethod
    async def generate_recommendation(request: GenerateRequest) -> GenerateResponse:
        """Return a mock recommendation matching the caller's context."""
        logger.info(
            "Mock AI generate | mode=%s | user=%s | correlation_id=%s",
            request.mode,
            request.context.user_id,
            request.correlation_id,
        )

        recommendations: list[RecommendationItem] = []

        if request.mode == GenerateMode.PERSONALIZED:
            recommendations = _personalized_mock(request)
        else:
            recommendations = _general_mock()

        return GenerateResponse(
            recommendations=recommendations,
            status="SUCCESS",
            message="[MOCK] Generated by stub provider — replace in M6",
            model_version=request.model_version,
        )


# ── Mock helpers ──────────────────────────────────────────────────────────────


def _personalized_mock(request: GenerateRequest) -> list[RecommendationItem]:
    """Build a context-aware mock recommendation (1–2 items)."""
    items: list[RecommendationItem] = []

    goal = request.context.health.goal
    recent = request.context.workout.recent_sessions

    if recent < 3:
        items.append(
            RecommendationItem(
                title="Tăng tần suất tập luyện",
                description=(
                    f"Bạn chỉ tập {recent} buổi trong 7 ngày qua. "
                    "Mục tiêu 3–4 buổi/tuần sẽ giúp cải thiện thể lực đáng kể."
                ),
                type=RecommendationType.WORKOUT,
            )
        )

    if goal and "LOSE" in goal.upper():
        daily_target = request.context.nutrition.daily_calories_target
        if daily_target:
            items.append(
                RecommendationItem(
                    title="Theo dõi lượng calo hôm nay",
                    description=(
                        f"Mục tiêu của bạn là {daily_target:.0f} kcal/ngày. "
                        "Ghi nhận bữa ăn đều đặn giúp bạn đạt mục tiêu nhanh hơn."
                    ),
                    type=RecommendationType.NUTRITION,
                )
            )

    # Ensure at least one item is returned
    if not items:
        items.append(
            RecommendationItem(
                title="Duy trì lịch tập hôm nay",
                description="Hãy hoàn thành buổi tập đã lên kế hoạch để giữ thói quen.",
                type=RecommendationType.WORKOUT,
            )
        )

    return items[:3]  # enforce 1–3 item contract


def _general_mock() -> list[RecommendationItem]:
    """Return a generic, non-personalised recommendation."""
    return [
        RecommendationItem(
            title="Khởi động trước khi tập",
            description=(
                "Dành 5–10 phút khởi động nhẹ giúp tăng lưu lượng máu "
                "và giảm nguy cơ chấn thương trong buổi tập."
            ),
            type=RecommendationType.GENERAL_ADVICE,
        )
    ]
