CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL,
    password_hash     VARCHAR(255),
    auth_provider     VARCHAR(20)  NOT NULL,
    provider_subject  VARCHAR(255),
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    email_verified_at TIMESTAMPTZ,
    last_login_at     TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_auth_provider
        CHECK (auth_provider IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT chk_users_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_users_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'LOCKED', 'DISABLED')),
    CONSTRAINT chk_users_local_password
        CHECK (auth_provider <> 'LOCAL' OR password_hash IS NOT NULL),
    CONSTRAINT chk_users_active_verified
        CHECK (status <> 'ACTIVE'
               OR auth_provider <> 'LOCAL'
               OR email_verified_at IS NOT NULL)
);

CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));
CREATE UNIQUE INDEX uq_users_provider_subject
    ON users (auth_provider, provider_subject)
    WHERE provider_subject IS NOT NULL;

-- §4.2 refresh_tokens -------------------------------------------------------
CREATE TABLE refresh_tokens (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL REFERENCES users (id),
    token_hash           VARCHAR(255) NOT NULL,
    status               VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    expires_at           TIMESTAMPTZ  NOT NULL,
    revoked_at           TIMESTAMPTZ,
    replaced_by_token_id BIGINT       REFERENCES refresh_tokens (id),
    device_info          VARCHAR(255),
    ip_address           INET,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_refresh_tokens_status
        CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    CONSTRAINT chk_refresh_tokens_revoked
        CHECK (status <> 'REVOKED' OR revoked_at IS NOT NULL)
);

CREATE INDEX idx_refresh_tokens_user_status
    ON refresh_tokens (user_id, status, expires_at);

-- §4.3 otp_codes ------------------------------------------------------------
CREATE TABLE otp_codes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       REFERENCES users (id),
    destination         VARCHAR(255) NOT NULL,
    purpose             VARCHAR(30)  NOT NULL,
    code_hash           VARCHAR(255) NOT NULL,
    attempt_count       SMALLINT     NOT NULL DEFAULT 0,
    max_attempts        SMALLINT     NOT NULL,
    expires_at          TIMESTAMPTZ  NOT NULL,
    resend_available_at TIMESTAMPTZ  NOT NULL,
    consumed_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_otp_codes_purpose
        CHECK (purpose IN ('REGISTER', 'PASSWORD_RESET')),
    CONSTRAINT chk_otp_codes_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT chk_otp_codes_max_attempts  CHECK (max_attempts > 0)
);

CREATE INDEX idx_otp_destination_purpose
    ON otp_codes (destination, purpose, created_at DESC);

-- §4.4 security_rate_limit_events --------------------------------------------
CREATE TABLE security_rate_limit_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope            VARCHAR(30)  NOT NULL,
    subject_key_hash VARCHAR(128) NOT NULL,
    ip_address       INET,
    succeeded        BOOLEAN      NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_security_rate_limit_scope
        CHECK (scope IN ('LOGIN', 'OTP_SEND', 'OTP_VERIFY'))
);

CREATE INDEX idx_security_rate_limit_subject
    ON security_rate_limit_events (scope, subject_key_hash, created_at DESC);

-- §4.5 user_profiles ----------------------------------------------------------
CREATE TABLE user_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id),
    display_name    VARCHAR(120) NOT NULL,
    avatar_media_id BIGINT,
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    locale          VARCHAR(10)  NOT NULL DEFAULT 'vi-VN',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_profiles_user UNIQUE (user_id)
);
