CREATE TABLE password_reset_proofs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    proof_hash  VARCHAR(128) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_password_reset_proofs_hash UNIQUE (proof_hash)
);

CREATE INDEX idx_password_reset_proofs_user_expiry
    ON password_reset_proofs (user_id, expires_at);
