-- M2-15 — Preference and equipment onboarding schema.
-- user_profiles is already created in V1__identity_and_profile.sql (§4.5); this
-- migration adds the remaining Identity & Profile preference tables (§4.6, §4.7)
-- plus the equipment master table (§6.1) required by the equipment-preference FK.

-- §6.1 equipment (workout master data; created here because the equipment
-- preference below references it. Remaining workout master tables — muscle_groups,
-- exercises and their mappings — are added in the workout milestone).
CREATE TABLE equipment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    is_active   BOOLEAN      NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_equipment_code UNIQUE (code)
);

-- §4.6 user_preferences ------------------------------------------------------
CREATE TABLE user_preferences (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                           BIGINT      NOT NULL REFERENCES users (id),
    disliked_foods                    JSONB       NOT NULL DEFAULT '[]',
    allergies                         JSONB       NOT NULL DEFAULT '[]',
    dietary_constraints               JSONB       NOT NULL DEFAULT '[]',
    meal_preferences                  JSONB       NOT NULL DEFAULT '{}',
    training_preferences              JSONB       NOT NULL DEFAULT '{}',
    preferred_training_time           TIME,
    equipment_onboarding_completed_at TIMESTAMPTZ,
    created_at                        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_preferences_user UNIQUE (user_id),
    CONSTRAINT chk_user_preferences_disliked_foods
        CHECK (jsonb_typeof(disliked_foods) = 'array'),
    CONSTRAINT chk_user_preferences_allergies
        CHECK (jsonb_typeof(allergies) = 'array'),
    CONSTRAINT chk_user_preferences_dietary_constraints
        CHECK (jsonb_typeof(dietary_constraints) = 'array'),
    CONSTRAINT chk_user_preferences_meal_preferences
        CHECK (jsonb_typeof(meal_preferences) = 'object'),
    CONSTRAINT chk_user_preferences_training_preferences
        CHECK (jsonb_typeof(training_preferences) = 'object')
);

-- §4.7 user_equipment_preferences --------------------------------------------
CREATE TABLE user_equipment_preferences (
    user_id      BIGINT      NOT NULL REFERENCES users (id),
    equipment_id BIGINT      NOT NULL REFERENCES equipment (id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_user_equipment_preferences PRIMARY KEY (user_id, equipment_id)
);

CREATE INDEX idx_user_equipment_preferences_equipment
    ON user_equipment_preferences (equipment_id);
