-- M2-16 — Health profile, nutrition target, and weight log schema.

CREATE TABLE health_profiles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT      NOT NULL,
    date_of_birth       DATE        NOT NULL,
    gender              VARCHAR(20) NOT NULL,
    calculation_sex     VARCHAR(20) NOT NULL DEFAULT 'UNSPECIFIED',
    height_cm           NUMERIC(5,2) NOT NULL,
    current_weight_kg   NUMERIC(6,2) NOT NULL,
    activity_level      VARCHAR(20) NOT NULL,
    fitness_goal        VARCHAR(30) NOT NULL,
    training_experience VARCHAR(30) NOT NULL,
    bmi                 NUMERIC(6,2) NOT NULL,
    bmr_kcal            NUMERIC(8,2),
    tdee_kcal           NUMERIC(8,2),
    calculation_version VARCHAR(30) NOT NULL,
    calculated_at       TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_health_profiles PRIMARY KEY (id),
    CONSTRAINT fk_health_profiles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_health_profiles_user UNIQUE (user_id),
    CONSTRAINT chk_health_profiles_gender
        CHECK (gender IN ('MALE', 'FEMALE', 'OTHER', 'UNSPECIFIED')),
    CONSTRAINT chk_health_profiles_calculation_sex
        CHECK (calculation_sex IN ('MALE', 'FEMALE', 'UNSPECIFIED')),
    CONSTRAINT chk_health_profiles_height_cm CHECK (height_cm > 0),
    CONSTRAINT chk_health_profiles_current_weight_kg CHECK (current_weight_kg > 0),
    CONSTRAINT chk_health_profiles_activity_level
        CHECK (activity_level IN ('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE')),
    CONSTRAINT chk_health_profiles_fitness_goal
        CHECK (fitness_goal IN ('LOSE_WEIGHT', 'MAINTAIN_WEIGHT', 'GAIN_WEIGHT', 'GAIN_MUSCLE')),
    CONSTRAINT chk_health_profiles_training_experience
        CHECK (training_experience IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED')),
    CONSTRAINT chk_health_profiles_bmi CHECK (bmi > 0),
    CONSTRAINT chk_health_profiles_bmr_kcal CHECK (bmr_kcal IS NULL OR bmr_kcal > 0),
    CONSTRAINT chk_health_profiles_tdee_kcal CHECK (tdee_kcal IS NULL OR tdee_kcal > 0)
);

CREATE TABLE nutrition_targets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT      NOT NULL,
    health_profile_id   BIGINT      NOT NULL,
    calories_kcal       NUMERIC(8,2) NOT NULL,
    protein_g           NUMERIC(7,2) NOT NULL,
    carbs_g             NUMERIC(7,2) NOT NULL,
    fat_g               NUMERIC(7,2) NOT NULL,
    calculation_version VARCHAR(30) NOT NULL,
    effective_from      TIMESTAMPTZ NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_nutrition_targets PRIMARY KEY (id),
    CONSTRAINT fk_nutrition_targets_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_nutrition_targets_health_profile
        FOREIGN KEY (health_profile_id) REFERENCES health_profiles (id),
    CONSTRAINT uq_nutrition_targets_user UNIQUE (user_id),
    CONSTRAINT chk_nutrition_targets_calories_kcal CHECK (calories_kcal > 0),
    CONSTRAINT chk_nutrition_targets_protein_g CHECK (protein_g >= 0),
    CONSTRAINT chk_nutrition_targets_carbs_g CHECK (carbs_g >= 0),
    CONSTRAINT chk_nutrition_targets_fat_g CHECK (fat_g >= 0)
);

CREATE TABLE weight_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT      NOT NULL,
    logged_date DATE        NOT NULL,
    weight_kg   NUMERIC(6,2) NOT NULL,
    note        VARCHAR(500),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_weight_logs PRIMARY KEY (id),
    CONSTRAINT fk_weight_logs_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_weight_logs_user_logged_date UNIQUE (user_id, logged_date),
    CONSTRAINT chk_weight_logs_weight_kg CHECK (weight_kg > 0)
);

CREATE INDEX idx_weight_logs_user_logged_date
    ON weight_logs (user_id, logged_date DESC);
