package com.viegym.common.error;

import org.springframework.http.HttpStatus;

public enum ApiErrorCode {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    TOKEN_REVOKED(HttpStatus.UNAUTHORIZED),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    ACCOUNT_PENDING(HttpStatus.FORBIDDEN),
    ACCOUNT_LOCKED(HttpStatus.FORBIDDEN),
    ACCOUNT_DISABLED(HttpStatus.FORBIDDEN),
    AI_CONSENT_REQUIRED(HttpStatus.FORBIDDEN),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    EXERCISE_NOT_FOUND(HttpStatus.NOT_FOUND),
    FOOD_NOT_FOUND(HttpStatus.NOT_FOUND),
    RESOURCE_HIDDEN(HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    ACTIVE_PROGRAM_EXISTS(HttpStatus.CONFLICT),
    ACTIVE_SESSION_EXISTS(HttpStatus.CONFLICT),
    INVALID_STATE_TRANSITION(HttpStatus.CONFLICT),
    SCHEDULE_NO_LONGER_PLANNED(HttpStatus.CONFLICT),
    DAY_HAS_PLANNED_SCHEDULES(HttpStatus.CONFLICT),
    RECOMMENDATION_NOT_PENDING(HttpStatus.CONFLICT),
    RECOMMENDATION_EXPIRED(HttpStatus.CONFLICT),
    IDEMPOTENCY_CONFLICT(HttpStatus.CONFLICT),
    OTP_INVALID(HttpStatus.BAD_REQUEST),
    OTP_EXPIRED(HttpStatus.BAD_REQUEST),
    OTP_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    OTP_COOLDOWN(HttpStatus.TOO_MANY_REQUESTS),
    RATE_LIMITED(HttpStatus.TOO_MANY_REQUESTS),
    DAILY_GENERATION_LIMIT_REACHED(HttpStatus.TOO_MANY_REQUESTS),
    PASSWORD_CHANGE_NOT_SUPPORTED(HttpStatus.UNPROCESSABLE_ENTITY),
    HEALTH_PROFILE_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY),
    HEALTH_CALCULATION_UNAVAILABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    SESSION_LOG_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    FOOD_NOT_SELECTABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    MEAL_TEMPLATE_ITEM_UNAVAILABLE(HttpStatus.UNPROCESSABLE_ENTITY),
    PROPOSAL_TARGET_INVALID(HttpStatus.UNPROCESSABLE_ENTITY),
    AI_PROVIDER_UNAVAILABLE(HttpStatus.BAD_GATEWAY),
    AI_OUTPUT_INVALID(HttpStatus.BAD_GATEWAY),
    MEDIA_SIZE_EXCEEDED(HttpStatus.PAYLOAD_TOO_LARGE),
    MEDIA_TYPE_NOT_SUPPORTED(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    MEDIA_MIME_MISMATCH(HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    UPLOAD_NOT_COMPLETED(HttpStatus.CONFLICT),
    UPLOAD_EXPIRED(HttpStatus.GONE),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;

    ApiErrorCode(HttpStatus httpStatus) {
        this.httpStatus = httpStatus;
    }

    public HttpStatus httpStatus() {
        return httpStatus;
    }
}
